### ISSUE TITLE
Review for [Kanban Board Setup] | Rails Group Project

### ISSUE THREAD

**Issue by luigirazum** [Log-benjamin/Recipe-app#13]
# Hello Dear Code Reviewers Team 👋,
### - 🚀 Project
>    ### 🍽️ Recipe App (Rails Group Project)

### - 📈 Kanban Board
> - [Recipe App Kanban Board](https://github.com/Log-benjamin/Recipe-app/projects/1)

### - 🧑‍💻 Team Members (2 People)
> - Binyam Tegene / @Log-benjamin
> - Luis Zubia / @luigirazum

### Binyam / Luis

**Comment by zieeco** [comment]
Hi @Team,

<img height="100" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Great effort setting up the kanban board ✔️
- Descriptive issue. ✔️


## Required Changes ♻️

_Check the comments under the review._

- [ ] Please, also consider adding a task for setting up your database, and models, as this is the main foundation for building every other part of your app. This should be defined in the Kanban board. This can also be a group task to foster collaboration between each team member. Please, kindly add this missing part to your Kanban board. :muscle: 



## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luigirazum** [comment]
Thanks @zieeco for the feedback.
- [X] The required task has been added to the Kanban Board.

**Comment by Davidosky007** [comment]
Hi @luigirazum @Log-benjamin 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Link to board works 👍 
* Descriptive issue 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luigirazum** [comment]
Thanks for the approval @Davidosky007!! 👏
